### PR TITLE
UIIN-1368: Update API endpoint for retrieving instances UUIDs

### PR DESCRIPTION
**Pull request by ViktorSoroka07**
## Purpose
Update API endpoint for retrieving instances UUIDs in the scope of the [UIIN-1368](https://issues.folio.org/browse/UIIN-1368).

### CODE REVIEW

**Review by yelyzavetakhokhlova — APPROVED** [review]

**Review by KVupp — COMMENTED** [review]
I think the permission re-name is missing, can you please change it in package.json

**Comment by KVupp** [comment]
Also was just curious why the interface is not listed under okapi Interfaces? https://github.com/folio-org/ui-inventory/blob/master/package.json#L45?

**Comment by ViktorSoroka07** [comment]
@KVupp, thank you. Handled permission renaming. Regarding the interface, since it works on the folio-snapshot it seems it is not needed in this case. Can it be so because some of the existing interfaces already include it?

**Comment by ViktorSoroka07** [comment]
As I see "item-storage": "8.0" provides it.

https://github.com/folio-org/mod-inventory-storage/blob/fa058c357b9197da653b4d74ed5edf1a2f503ac5/descriptors/ModuleDescriptor-template.json

**Comment by KVupp** [comment]
> As I see "item-storage": "8.0" provides it.
> 
> https://github.com/folio-org/mod-inventory-storage/blob/fa058c357b9197da653b4d74ed5edf1a2f503ac5/descriptors/ModuleDescriptor-template.json

item-storage itself is an interface Viktor, and instance-bulk is it's own interface. If it works on snapshot, it might not necessarily mean it is not needed, Atleast on the backend we use it to resolve dependencies. Probably better to confirm regarding the front end as well

**Comment by ViktorSoroka07** [comment]
Gotcha, I have added the interface just in case.

**Comment by KVupp** [comment]
> Gotcha, I have added the interface just in case.

Thanks Viktor!

**Pull request merged**
