### PR TITLE
UIIN-2781: Do not show separator for first facets, remove the input field for facets with Yes/No options and for the Source facet.

### PR DESCRIPTION
**Pull request by Dmytro-Melnyshyn**
Follow-up PR.

## Purpose
- add a separator to facets;
- do not show the separator for the first facets;
- remove the input field for facets with `Yes/No` options;
- remove the input field from the `Source` facet.

## Related PRs
https://github.com/folio-org/stripes-inventory-components/pull/46

## Refs
[UIIN-2781](https://folio-org.atlassian.net/browse/UIIN-2781)

## Screenshots

https://github.com/folio-org/ui-inventory/assets/77053927/fb0e3d77-5195-4aba-b342-5ec89f41630f

### CODE REVIEW

**Review by artem-blazhko — COMMENTED** [review]
Could you update CHANGELOG file and get rid of code duplication?

**Review by mariia-aloshyna — APPROVED** [review]
update CHANGELOG pls

**Comment by artem-blazhko** [comment]
> > Could you update CHANGELOG file and get rid of code duplication?
> 
> @artem-blazhko - we do not update the changelog for follow-up PRs. Can you point me to code duplication?

Sorry, I did not see that it is follow-up PR.

Regarding code duplication
image

**Comment by Dmytro-Melnyshyn** [comment]
> > > Could you update CHANGELOG file and get rid of code duplication?
> > 
> > 
> > @artem-blazhko - we do not update the changelog for follow-up PRs. Can you point me to code duplication?
> 
> Sorry, I did not see that it is follow-up PR.
> 
> Regarding code duplication image

@artem-blazhko - those duplications are not related to any code changes I made. I just added a new prop for the <EffectiveLocationFacet />.

**Review by artem-blazhko — APPROVED** [review]

**Pull request merged**
