### PR TITLE
UIIN-1866 Holdings. Keyboard shortcuts does not act on the holdings

### PR DESCRIPTION
**Pull request by usavkov-epam**
## Purpose

The root reason for this pull request is https://issues.folio.org/browse/UIIN-1866.

Combining layers and shortcuts causes unexpected bugs like the one above. If there is no shortcut handler (e.g. for duplication) for any layer, it is pulled from the parent component. This is logical, but not always expected - the user, being in the holding's view, will be confused by using `Cmd + C` shortcut and seeing as a result the form for creating an instance instead of holding. Or an user applies `Option + N` shortcut in the holding's edit form  - as a result, he will be redirected to the form for creating a new instance - it's confusing. 

This problem could be solved by adding handlers for the necessary shortcuts or stubs for unnecessary ones, but this approach is unstable and may require improvement in the future. _What if the parent component adds a batch of shortcuts that are unnecessary for another layer?_

Since our team has some capacity, we decided to make additional routing for the holding forms, thus eliminating the original bug, the massive component becomes less loaded, the routing becomes more obvious.
## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [x] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [x] Code coverage on new code is 80% or greater
  - [x] Duplications on new code is 3% or less
  - [x] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

### CODE REVIEW

**Comment by mkuklis** [comment]
@usavkov-epam this looks great but the description of this ticket mentions issues with the keyboard and when I look at the PR I see a big refactoring related to duplicating a holding. Would you mind providing a couple details about what has change here and wy?

**Comment by usavkov-epam** [comment]
@mkuklis I have updated the description of this PR to describe the purpose of this refactoring)

**Comment by NikitaSedyx** [comment]
@mkuklis we'll have one more similar request soon, but for items

**Comment by mkuklis** [comment]
Thank you @usavkov-epam!

**Review by mkuklis — APPROVED** [review]
This looks great! Thank you for the extra refactoring and the description.

**Review by NikitaSedyx — APPROVED** [review]

**Review by Baroquem — APPROVED** [review]

**Review by NikitaSedyx — APPROVED** [review]

**Pull request merged**
