### PR TITLE
UIIN-1617 Item count bug when there are multiple holdings on an instance

### PR DESCRIPTION
**Pull request by usavkov-epam**
## Purpose

https://issues.folio.org/browse/UIIN-1617
## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [x] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [x] Code coverage on new code is 80% or greater
  - [x] Duplications on new code is 3% or less
  - [x] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [x] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

### CODE REVIEW

**Review by NikitaSedyx — APPROVED** [review]

**Review by AndreiShumski2 — APPROVED** [review]

**Review by mkuklis — COMMENTED** [review]
@usavkov-epam it's nice to see that you refactored it to use `React Query`.

The one issue which would be nice to change here is to not retrieve all items because we may run into performance issues which the previous PR related to this work was trying to resolve.

Would it be possible to set a `limit=1` in `useHoldingItemsQuery` and use `totalRecords` returned from the server in a similar fashion to how this was setup before via `stripes-connect`?

Or is that endpoint not returning correct totals?

**Comment by usavkov-epam** [comment]
> @usavkov-epam it's nice to see that you refactored it to use `React Query`.
> 
> The one issue which would be nice to change here is to not retrieve all items because we may run into performance issues which the previous PR related to this work was trying to resolve.
> 
> Would it be possible to set a `limit=1` in `useHoldingItemsQuery` and use `totalRecords` returned from the server in a similar fashion to how this was setup before via `stripes-connect`?
> 
> Or is that endpoint not returning correct totals?

@mkuklis Yes it is possible. How do you look to make some changes in `useHoldingItemsQuery` like these:
```
// useHoldingItemsQuery.js 

const useHoldingItemsQuery = (
  holdingsRecordId,
  options = { searchParams: {} },
) => {
  const ky = useOkapiKy();
  const [namespace] = useNamespace();
  const queryKey = [namespace, 'items', holdingsRecordId];
  const defaultSearchParams = {
    limit: LIMIT_MAX,
    query: `holdingsRecordId==${holdingsRecordId}`,
  };

  const searchParams = {
    ...defaultSearchParams,
    ...options.searchParams,
  };

  const queryFn = () => ky.get('inventory/items', { searchParams }).json();
  const { data, isLoading, isFetching } = useQuery({ queryKey, queryFn, ...options });

  return {
    isFetching,
    isLoading,
    items: data?.items,
    totalRecords: data?.totalRecords,
  };
};
```

Then we can pass the limit:
```
// HoldingAccordion.js

 const searchParams = {
    limit: 1,
  };
  const { totalRecords, isFetching } = useHoldingItemsQuery(holding.id, { searchParams });
```

**Comment by mkuklis** [comment]
Looks great @usavkov-epam. Thank you! Do you get a correct value under `totalRecords` when you set the limit to 1?

**Review by mkuklis — APPROVED** [review]

**Comment by usavkov-epam** [comment]
> Looks great @usavkov-epam. Thank you! Do you get a correct value under `totalRecords` when you set the limit to 1?
@mkuklis Yeap, with the set `limit=1` the value of the `totalRecords` is correct)

**Review by Baroquem — APPROVED** [review]

**Pull request merged**
