### PR TITLE
UIIN-2196: Relabel bound-with accordion

### PR DESCRIPTION
**Pull request by maccabeelevine**
## Purpose
This accordion on the item view (and eventually on holdings view) displays more than just bound-with data.

## Approach
Simple rename of the label in en.json.

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [X] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [X] Duplications on new code is 3% or less
  - [X] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [X] There are no breaking changes in this PR.

## Issues
https://issues.folio.org/browse/UIIN-2196

### CODE REVIEW

**Comment by maccabeelevine** [comment]
@mkuklis or @nielserik for your review please.  @CharlotteWhitt can add more detail on the purpose of the relabel if needed.

**Review by mkuklis — APPROVED** [review]

**Comment by maccabeelevine** [comment]
Forgot to note here that I don't have permission to merge this, please do so if appropriate.

**Comment by mkuklis** [comment]
@maccabeelevine would you mind requesting access to ui-inventory on slack under devops channel? After you get access please clone the repo and re-open the same PR and we can re-approve it again. After that you should be able to merge your work.

**Comment by maccabeelevine** [comment]
Replaced with https://github.com/folio-org/ui-inventory/pull/1799

**Pull request closed without merging**
