### PR TITLE
handle i18n props correctly. Fixes UIIN-172

### PR DESCRIPTION
**Pull request by zburke**
Fixes [UIIN-172](https://issues.folio.org/browse/UIIN-172)

### CODE REVIEW

**Comment by MikeTaylor** [comment]
What is the difference between the behaviour of the old and the new code?

**Comment by zburke** [comment]
The `props` value handed into `validate` is provided by `redux-form` and does not contain `stripes`. Thus, we must use `<FormattedMessage />` because `props.stripes.intl.formatMessage()` is not available.

**Comment by MikeTaylor** [comment]
Wow, that's a nice subtlety! Thanks for explaining.

**Comment by zburke** [comment]
I take that back, sort of. The `props` value provided to `validate` by `redux-form` contains the same `{...props}` that were passed into `ItemForm`, so the issue this case is that we never passed `stripes` to `ItemForm` from `ViewItem` in the first place.

**Pull request merged**
