### PR TITLE
UIIN-1404 Update to match changed mod-copycat API

### PR DESCRIPTION
**Pull request by MikeTaylor**
This relates to externally visible changes made to mod-copycat in [pull-request 18](https://github.com/folio-org/mod-copycat/pull/18/files)

Interface names:
* Interface name `copycat-targetprofiles` changed to `copycat-profiles`

WSAPI paths:
* Path `/copycat/target-profiles` changed to `/copycat/profiles`
* Path `/copycat/target-profiles/{id}` changed to `/copycat/profiles/{id}`

Permissions names:
* Permission name `copycat.target-profiles.item.post` changed to `copycat.profiles.item.post`
* Permission name `copycat.target-profiles.collection.get` changed to `copycat.profiles.collection.get`
* Permission name `copycat.target-profiles.item.get` changed to `copycat.profiles.item.get`
* Permission name `copycat.target-profiles.item.put` changed to `copycat.profiles.item.put`
* Permission name `copycat.target-profiles.item.delete` changed to `copycat.profiles.item.delete`

Schema elements
* In `copycatimports.json`, `targetProfileId` renamed `profileId`
* In `copycatimports.json`, `record` added (to contain MARC record)
* In `copycatimports.json`, `externalIdentifier` made mandatory
* In `copycattargetcollection.json`, `targetprofiles` renamed `profiles`
* In `copycattargetprofile.json`, `importProfileId` renamed `jobProfileId`
* In `copycattargetprofile.json`, `url` and `externalIdQueryMap` are no longer mandatory

(Raml type names and JSON Schema file names have also changed, but these do not affect the client code.)

### CODE REVIEW

**Review by zburke — CHANGES_REQUESTED** [review]
Adding an interface is a major change. Please update the major version in `package.json` and add a note to the CHANGELOG. Additionally, please link to the JIRA that describes this work so we can track the feature and version change there.

**Comment by MikeTaylor** [comment]
Excellent points, thank you.

(The timing is off, though: I have been _using_ the interface for a while undeclared, and only now added it to the package file. So I really should have incremented the major version number a while ago.)

**Comment by MikeTaylor** [comment]
(But all this is academic while tests can't pass and PRs can't be merged.)

**Comment by MikeTaylor** [comment]
@zburke I added a change-logging entry noting the addition of two new interfaces. But since there was already a v6.0.0 heading in the change-log — and so the code presumably already included major changes — I did not increment the actual version number in the package file. I assume that whoever manages this app prefers to do that as part of the release process.

**Pull request closed without merging**
