### PR TITLE
Merge changes for UIIN-627

### PR DESCRIPTION
**Pull request by Baroquem**
Fix bug affecting display of warning messages in settings (UIIN-627)

### CODE REVIEW

**Comment by mkuklis** [comment]
@Baroquem please try to rebase with master. The tests should pass again.

**Comment by mkuklis** [comment]
Matt something doesn't look right here because I now see the changes from other PRs.

**Comment by Baroquem** [comment]
Hmm, you're right ... let me try that again.

**Comment by zburke** [comment]
Replaced by #678.

**Pull request closed without merging**
