### PR TITLE
UIIN-2094: browse contributors may show results floating amid blank rows

### PR DESCRIPTION
**Pull request by Dmytro-Melnyshyn**
## Purpose
- changing a select-option should not submit a form
- results pane shouldn't show blank rows

## Approach
- as for changing a "select-option should not submit a form": use the 'fetch' function to determine if the fetch should execute or not.
- as for empty rows: the column headings are different for the browse options, so the rows are displayed without data. Now after selecting any browse option, the records will be reset.

https://user-images.githubusercontent.com/77053927/179087298-263f85ea-7fba-4dc7-a88f-0ae9a7f6e09f.mp4

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

### CODE REVIEW

**Review by BogdanDenis — COMMENTED** [review]
I think adding a new resource to manifest and related logic might be an overkill - it seems that the problem is that url is updated when user in making changes to index, even though it shouldn't happen.
We can fix it be removing `qindex` from `parentMutator.query.update` call inside `onChangeIndex`
This way local state will be updated and url won't change until submit button is clicked
Could you check if this solution works please?

**Comment by Dmytro-Melnyshyn** [comment]
> I think adding a new resource to manifest and related logic might be an overkill - it seems that the problem is that url is updated when user in making changes to index, even though it shouldn't happen. We can fix it be removing `qindex` from `parentMutator.query.update` call inside `onChangeIndex` This way local state will be updated and url won't change until submit button is clicked Could you check if this solution works please?

Thanks for the comment. It will work if filters are not selected. `parentMutator.query.update` also removes filters from the URL.

**Review by BogdanDenis — APPROVED** [review]

**Comment by mkuklis** [comment]
@Dmytro-Melnyshyn the `fetch` could be also a function which can be used to determine if the fetch should execute or not (by returning `true` or `false`). It receives current props of the connected component. Perhaps there is something in the props which can be used to control the fetch? Have you explored that approach? It would be really nice not to introduce that extra local resource (`manifestFetchPropToSearch`).

**Review by mkuklis — APPROVED** [review]

**Comment by Dmytro-Melnyshyn** [comment]
> @Dmytro-Melnyshyn the `fetch` could be also a function which can be used to determine if the fetch should execute or not (by returning `true` or `false`). It receives current props of the connected component. Perhaps there is something in the props which can be used to control the fetch? Have you explored that approach? It would be really nice not to introduce that extra local resource (`manifestFetchPropToSearch`).

@mkuklis thanks for the comment, I've changed the approach, please have a look.

**Review by BogdanDenis — APPROVED** [review]

**Review by mkuklis — APPROVED** [review]
@Dmytro-Melnyshyn thank you for exploring this further. Nice work!

**Pull request merged**
